In [2]:
import numpy as np

In [3]:
a_list = [1,2,3,4]
a_list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
an_array = np.array(a_list)
an_array * 2

array([2, 4, 6, 8])

In [5]:
nested_list = [[1,2,3],[4,5,6],[7,8,9]]
nested_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
nested_array = np.array(nested_list)
print(nested_array)
print(nested_array[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]


In [7]:
sudoku_0 = [
    [0,6,3,5,8,4,0,0,0],
    [0,2,7,0,0,0,0,8,0],
    [0,0,0,2,0,0,9,0,3],
    [0,3,0,6,0,0,8,0,0],
    [0,0,0,8,5,9,0,0,0],
    [0,0,5,0,0,7,0,4,0],
    [2,0,8,0,0,5,0,0,0],
    [0,4,0,0,0,0,5,3,0],
    [0,0,0,4,9,8,7,1,0]
]
sudoku_0 = np.array(sudoku_0)

In [61]:
# Display the board
def display(sudoku_board):
    for i,row in enumerate(sudoku_board):
        for j,entry in enumerate(row):
            if j in (2,5):
                print(entry,end=" | ")
            else:
                print(entry,end=" ")
        print()
        if i in (2,5):
            print("---------------------")
    return 

In [62]:
display(sudoku_0)

0 6 3 | 5 8 4 | 0 0 0 
0 2 7 | 0 0 0 | 0 8 0 
0 0 0 | 2 0 0 | 9 0 3 
---------------------
0 3 0 | 6 0 0 | 8 0 0 
0 0 0 | 8 5 9 | 0 0 0 
0 0 5 | 0 0 7 | 0 4 0 
---------------------
2 0 8 | 0 0 5 | 0 0 0 
0 4 0 | 0 0 0 | 5 3 0 
0 0 0 | 4 9 8 | 7 1 0 


In [63]:
# Look at the number that shows up the most on the board
def strat2(sudoku_board_in):
    sudoku_board = sudoku_board_in.__deepcopy__(sudoku_board_in)
    numbers = (1,2,3,4,5,6,7,8,9)
    boxes = [
        sudoku_board[0:3,0:3], # rows 0,1,2, columns 0,1,2
        sudoku_board[0:3,3:6], # rows 0,1,2, columns 3,4,5
        sudoku_board[0:3,6:9], # rows 0,1,2, columns 6,7,8
        sudoku_board[3:6,0:3], # rows 3,4,5, columns 0,1,2
        sudoku_board[3:6,3:6], # rows 3,4,5, columns 3,4,5
        sudoku_board[3:6,6:9],
        sudoku_board[6:9,0:3], # rows 6,7,8
        sudoku_board[6:9,3:6],
        sudoku_board[6:9,6:9],
    ]
    for number in numbers:
        for box_index,box in enumerate(boxes):
            if number not in box.flatten():
                candidates = [
                    [1,1,1],
                    [1,1,1],
                    [1,1,1]
                ]
                # Look through each candidate
                for i in (0,1,2):
                    for j in (0,1,2):
                        # If this position is already taken up by a number
                        if box[i,j] in numbers:
                            # Eliminate the candidate
                            candidates[i][j] = 0
                        # If there's no number in that position
                        else:
                            row = (box_index//3)*3 + i 
                            column = (box_index%3)*3 + j
                            # If the number we investigating is in the row or column
                            if (number in sudoku_board[row,:]) or (number in sudoku_board[:,column]):
                                # Eliminate the candidate
                                candidates[i][j] = 0
                # Count how many possible candidates remaining
                num_candidates = np.sum(np.array(candidates).flatten())
                # If only one candidate remaining, fill it up
                if num_candidates == 1:
                    # get the index
                    i,j = np.where(np.array(candidates)==1)
                    i = int(i[0])
                    j = int(j[0])
                    candidate_row = (box_index//3)*3 + i 
                    candidate_column = (box_index%3)*3 + j
                    sudoku_board[candidate_row,candidate_column] = number 
                    print("HURRAY!")
    return sudoku_board 

In [64]:
# Look at the number that shows up the most on the board
def strat1(sudoku_board_in):
    sudoku_board = sudoku_board_in.__deepcopy__(sudoku_board_in)
    numbers = (1,2,3,4,5,6,7,8,9)
    highest = None
    for n in numbers:
        occurences = np.sum(sudoku_board.flatten()==n)
        if highest == None:
            highest = (n,occurences)
        elif occurences > highest[1]:
            highest = (n,occurences)
    boxes = [
        sudoku_board[0:3,0:3], # rows 0,1,2, columns 0,1,2
        sudoku_board[0:3,3:6], # rows 0,1,2, columns 3,4,5
        sudoku_board[0:3,6:9], # rows 0,1,2, columns 6,7,8
        sudoku_board[3:6,0:3], # rows 3,4,5, columns 0,1,2
        sudoku_board[3:6,3:6], # rows 3,4,5, columns 3,4,5
        sudoku_board[3:6,6:9],
        sudoku_board[6:9,0:3], # rows 6,7,8
        sudoku_board[6:9,3:6],
        sudoku_board[6:9,6:9],
    ]
    for box_index,box in enumerate(boxes):
        if highest[0] not in box.flatten():
            candidates = [
                [1,1,1],
                [1,1,1],
                [1,1,1]
            ]
            # Look through each candidate
            for i in (0,1,2):
                for j in (0,1,2):
                    # If this position is already taken up by a number
                    if box[i,j] in numbers:
                        # Eliminate the candidate
                        candidates[i][j] = 0
                    # If there's no number in that position
                    else:
                        row = (box_index//3)*3 + i 
                        column = (box_index%3)*3 + j
                        # If the number we investigating is in the row or column
                        if (highest[0] in sudoku_board[row,:]) or (highest[0] in sudoku_board[:,column]):
                            # Eliminate the candidate
                            candidates[i][j] = 0
            # Count how many possible candidates remaining
            num_candidates = np.sum(np.array(candidates).flatten())
            # If only one candidate remaining, fill it up
            if num_candidates == 1:
                # get the index
                i,j = np.where(np.array(candidates)==1)
                i = int(i[0])
                j = int(j[0])
                candidate_row = (box_index//3)*3 + i 
                candidate_column = (box_index%3)*3 + j
                sudoku_board[candidate_row,candidate_column] = highest[0]
                print("HURRAY!")
    return sudoku_board 

In [65]:
display(sudoku_0)


0 6 3 | 5 8 4 | 0 0 0 
0 2 7 | 0 0 0 | 0 8 0 
0 0 0 | 2 0 0 | 9 0 3 
---------------------
0 3 0 | 6 0 0 | 8 0 0 
0 0 0 | 8 5 9 | 0 0 0 
0 0 5 | 0 0 7 | 0 4 0 
---------------------
2 0 8 | 0 0 5 | 0 0 0 
0 4 0 | 0 0 0 | 5 3 0 
0 0 0 | 4 9 8 | 7 1 0 


In [66]:
display(strat2(strat2(sudoku_0)))

HURRAY!
HURRAY!
HURRAY!
HURRAY!
HURRAY!
HURRAY!
HURRAY!
HURRAY!
9 6 3 | 5 8 4 | 0 0 0 
0 2 7 | 9 0 0 | 0 8 0 
0 0 0 | 2 7 0 | 9 0 3 
---------------------
0 3 0 | 6 4 0 | 8 0 0 
0 0 0 | 8 5 9 | 0 0 0 
0 0 5 | 0 0 7 | 0 4 0 
---------------------
2 0 8 | 0 0 5 | 0 0 0 
0 4 0 | 0 0 0 | 5 3 8 
3 5 0 | 4 9 8 | 7 1 2 


In [67]:
np.where(np.array([[1,3],[3,3]]) == 3)

(array([0, 1, 1]), array([1, 0, 1]))

In [ ]:
i,j = np.where(np.array([[1,2],[3,4]]) == 3)
int(i[0])

1

In [11]:
arr = np.array([[1,2],[1,3]])
print(np.sum(arr.flatten()==1))

2


In [28]:
5%3

2

In [58]:
a = np.array([1,2])
b=a.__deepcopy__(a)
a[0]=5

In [59]:
a

array([5, 2])

In [60]:
b

array([1, 2])