In [93]:
import numpy as np
import copy

In [69]:
a_list = [1,2,3,4]
a_list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [70]:
an_array = np.array(a_list)
an_array * 2

array([2, 4, 6, 8])

In [71]:
nested_list = [[1,2,3],[4,5,6],[7,8,9]]
nested_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [72]:
nested_array = np.array(nested_list)
print(nested_array)
print(nested_array[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]


In [73]:
sudoku_0 = [
    [0,6,3,5,8,4,0,0,0],
    [0,2,7,0,0,0,0,8,0],
    [0,0,0,2,0,0,9,0,3],
    [0,3,0,6,0,0,8,0,0],
    [0,0,0,8,5,9,0,0,0],
    [0,0,5,0,0,7,0,4,0],
    [2,0,8,0,0,5,0,0,0],
    [0,4,0,0,0,0,5,3,0],
    [0,0,0,4,9,8,7,1,0]
]
sudoku_0 = np.array(sudoku_0)

In [227]:
sudoku_1 = [
    [0,0,0,0,0,0,3,0,0],
    [0,6,3,0,1,2,0,4,0],
    [7,0,0,5,0,0,0,0,0],
    [6,0,0,0,0,9,2,5,0],
    [0,9,0,0,0,0,0,6,0],
    [0,7,2,8,0,0,0,0,9],
    [0,0,0,0,0,8,0,0,5],
    [0,1,0,2,4,0,9,8,0],
    [0,0,4,0,0,0,0,0,0]
]
sudoku_1 = np.array(sudoku_1)

In [94]:
a=[[0]*2]*2
print(a)

[[0, 0], [0, 0]]


In [119]:
[[0]*3]*3

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [131]:
a = ["apple","banana"]
for idx,thing in enumerate(a):
    print(f"idx is {idx}, thing is {thing}")

idx is 0, thing is apple
idx is 1, thing is banana


In [170]:
# (untested)
# Get the board of 
def get_sudoku_iceberg(sudoku_board):
    sudoku_iceberg = [[[candidate for candidate in range(1,10)] for _ in range(9)] for _ in range(9)]
    for row_idx,row in enumerate(sudoku_board):
        for col_idx,square in enumerate(row):
            if square != 0:
                sudoku_iceberg[row_idx][col_idx] = [int(square)]
    return sudoku_iceberg
# get a board from iceberg
def get_sudoku_board_from_iceberg(sudoku_iceberg):
    sudoku_board = [[0 for _ in range(9)] for _ in range(9)]
    for row_idx in range(9):
        for col_idx in range(9):
            if len(sudoku_iceberg[row_idx][col_idx]) == 1:
                sudoku_board[row_idx][col_idx] = sudoku_iceberg[row_idx][col_idx][0]
    return np.array(sudoku_board)

In [171]:
display(sudoku_0)

0 6 3 | 5 8 4 | 0 0 0 
0 2 7 | 0 0 0 | 0 8 0 
0 0 0 | 2 0 0 | 9 0 3 
---------------------
0 3 0 | 6 0 0 | 8 0 0 
0 0 0 | 8 5 9 | 0 0 0 
0 0 5 | 0 0 7 | 0 4 0 
---------------------
2 0 8 | 0 0 5 | 0 0 0 
0 4 0 | 0 0 0 | 5 3 0 
0 0 0 | 4 9 8 | 7 1 0 


In [172]:
get_sudoku_iceberg(sudoku_0)


[[[1, 2, 3, 4, 5, 6, 7, 8, 9],
  [6],
  [3],
  [5],
  [8],
  [4],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9]],
 [[1, 2, 3, 4, 5, 6, 7, 8, 9],
  [2],
  [7],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [8],
  [1, 2, 3, 4, 5, 6, 7, 8, 9]],
 [[1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [2],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [3]],
 [[1, 2, 3, 4, 5, 6, 7, 8, 9],
  [3],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [6],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [8],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9]],
 [[1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [8],
  [5],
  [9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9]],
 [[1, 2,

In [225]:
# Removes all candidates from iceberg that are in the same box, row, or column
def iceberg_strat1(sudoku_iceberg_input):
    sudoku_iceberg = copy.deepcopy(sudoku_iceberg_input)
    sudoku_board = get_sudoku_board_from_iceberg(sudoku_iceberg)
    # Iterate through all squares 
    for row_idx in range(9):
        for col_idx in range(9):
            if sudoku_board[row_idx][col_idx] != 0:
                # Double check just as sanity
                assert len(sudoku_iceberg[row_idx][col_idx]) == 1
                continue 
            assert len(sudoku_iceberg[row_idx][col_idx]) > 1
            # Go through the list of possibile candidates in the iceberg and rule them out
            for candidate in sudoku_iceberg[row_idx][col_idx]:
                # Rule out the candidate if it appears in the same box
                box_row_idx = row_idx // 3 
                box_col_idx = col_idx // 3
                box = sudoku_board[box_row_idx*3:box_row_idx*3+3, box_col_idx*3:box_col_idx*3+3]
                # If the candidate is in the same box on the board
                if candidate in box.flatten():
                    # Remove the candidate from the candidates list
                    sudoku_iceberg[row_idx][col_idx].remove(candidate)
                # Rule out the candidate if it appears in the same row 
                elif candidate in sudoku_board[row_idx,:]:
                    # Remove the candidate from the list
                    sudoku_iceberg[row_idx][col_idx].remove(candidate)
                # Rule out the candidate if it appears in the same column
                elif candidate in sudoku_board[:,col_idx]:
                    # remove the candidate from the list
                    sudoku_iceberg[row_idx][col_idx].remove(candidate) 
    return sudoku_iceberg 



def iceberg_strat2(sudoku_iceberg_input):
    sudoku_iceberg = copy.deepcopy(sudoku_iceberg_input)
    sudoku_board = get_sudoku_board_from_iceberg(sudoku_iceberg)
    # Look through each square
    for row_idx in range(9):
        for col_idx in range(9):
            if sudoku_board[row_idx][col_idx] != 0:
                # Double check just as sanity
                assert len(sudoku_iceberg[row_idx][col_idx]) == 1
                continue 
            assert len(sudoku_iceberg[row_idx][col_idx]) > 1
            # Go through the list of possibile candidates in the iceberg and rule them out
            for candidate in sudoku_iceberg[row_idx][col_idx]:
                #if row_idx==0 and col_idx==6:
                #    print("candidates at 0,6:", sudoku_iceberg[0][6])
                # If that candidate does not appear as a candidate in any other square of box, row, or col
                # Starting with the box
                box_row_idx = row_idx // 3 
                box_col_idx = col_idx // 3
                box = sudoku_iceberg[box_row_idx*3:box_row_idx*3+3][box_col_idx*3:box_col_idx*3+3]
                flat_box = []
                for row in box:
                    for square in row:
                        for candidate2 in square:
                            flat_box.append(candidate2)
                # Count the number of appearances of our candidate 
                candidate_appearances = np.sum(np.array(flat_box) == candidate)
                if candidate_appearances == 1:
                    #print("row idx:",row_idx,"col_idx:",col_idx,"candidate:",candidate,"\nbox:",box,"\nflat_box:",flat_box,"\n")
                    # Then elimiate all other candidate of this sqaure we're checking 
                    sudoku_iceberg[row_idx][col_idx] = [candidate]
                    break 
                # If candidate does not appear as a candidate in any other square of the row... 
                row = sudoku_iceberg[row_idx]
                flat_row = []
                for square in row:
                    for candidate2 in square:
                        flat_row.append(candidate2)
                # Count the number of appearence of our candidate 
                candidate_appearances = np.sum(np.array(flat_row) == candidate)
                if candidate_appearances == 1:
                    #print("row idx:",row_idx,"col_idx:",col_idx,"candidate:",candidate,"\nrow:",row,"\nflat_row:",flat_row,"\n")
                    # Eliminate all other candidates of this square we're checking 
                    sudoku_iceberg[row_idx][col_idx] = [candidate]
                    break 
                # If candidate does not appear as a caniddate in any other square of the column...
                col = [row[col_idx] for row in sudoku_iceberg]
                flat_col = []
                for square in col:
                    for candidate2 in square:
                        flat_col.append(candidate2)
                # Counte the number of appearances of our candidate
                candidate_appearances = np.sum(np.array(flat_col) == candidate)
                if candidate_appearances == 1:
                    #print("row idx:",row_idx,"col_idx:",col_idx,"candidate:",candidate,"\ncol:",col,"\nflat_col:",flat_col,"\n")
                    # Eliminate all other candidates of this square we're checking 
                    sudoku_iceberg[row_idx][col_idx] = [candidate]
                    break 
    return sudoku_iceberg

In [229]:
sudoku_iceberg = get_sudoku_iceberg(sudoku_1)
for _ in range(100):
    sudoku_iceberg = iceberg_strat1(sudoku_iceberg)
    #print("candidates at row 0, col 6 after running strat1",sudoku_iceberg[0][6])
    sudoku_iceberg = iceberg_strat2(sudoku_iceberg)
display(sudoku_1)
print("\nx-x-x-x-x-x-x-x-x-x-x\n")
display(get_sudoku_board_from_iceberg(sudoku_iceberg))

0 0 0 | 0 0 0 | 3 0 0 
0 6 3 | 0 1 2 | 0 4 0 
7 0 0 | 5 0 0 | 0 0 0 
---------------------
6 0 0 | 0 0 9 | 2 5 0 
0 9 0 | 0 0 0 | 0 6 0 
0 7 2 | 8 0 0 | 0 0 9 
---------------------
0 0 0 | 0 0 8 | 0 0 5 
0 1 0 | 2 4 0 | 9 8 0 
0 0 4 | 0 0 0 | 0 0 0 

x-x-x-x-x-x-x-x-x-x-x

0 0 0 | 0 0 0 | 3 0 0 
0 6 3 | 0 1 2 | 5 4 0 
7 0 0 | 5 0 0 | 0 0 0 
---------------------
6 0 0 | 0 0 9 | 2 5 0 
0 9 0 | 0 2 0 | 0 6 0 
0 7 2 | 8 0 0 | 1 3 9 
---------------------
0 0 0 | 0 0 8 | 4 0 5 
0 1 0 | 2 4 0 | 9 8 0 
0 0 4 | 0 0 0 | 0 0 0 


In [74]:
# Display the board
def display(sudoku_board):
    for i,row in enumerate(sudoku_board):
        for j,entry in enumerate(row):
            if j in (2,5):
                print(entry,end=" | ")
            else:
                print(entry,end=" ")
        print()
        if i in (2,5):
            print("---------------------")
    return 

In [76]:
display(sudoku_0)

0 6 3 | 5 8 4 | 0 0 0 
0 2 7 | 0 0 0 | 0 8 0 
0 0 0 | 2 0 0 | 9 0 3 
---------------------
0 3 0 | 6 0 0 | 8 0 0 
0 0 0 | 8 5 9 | 0 0 0 
0 0 5 | 0 0 7 | 0 4 0 
---------------------
2 0 8 | 0 0 5 | 0 0 0 
0 4 0 | 0 0 0 | 5 3 0 
0 0 0 | 4 9 8 | 7 1 0 


In [ ]:
# For each number do start 1
def strat1(sudoku_board_in):
    sudoku_board = sudoku_board_in.__deepcopy__(sudoku_board_in)
    numbers = (1,2,3,4,5,6,7,8,9)
    # These are the 9 sub-boxes, call these boxes 
    boxes = [
        sudoku_board[0:3,0:3], # rows 0,1,2, columns 0,1,2
        sudoku_board[0:3,3:6], # rows 0,1,2, columns 3,4,5
        sudoku_board[0:3,6:9], # rows 0,1,2, columns 6,7,8
        sudoku_board[3:6,0:3], # rows 3,4,5, columns 0,1,2
        sudoku_board[3:6,3:6], # rows 3,4,5, columns 3,4,5
        sudoku_board[3:6,6:9],
        sudoku_board[6:9,0:3], # rows 6,7,8
        sudoku_board[6:9,3:6],
        sudoku_board[6:9,6:9],
    ]
    # Goes through all the numbers
    for number in numbers:
        # for each number, goes through all the boxes
        for box_index,box in enumerate(boxes):
            # for each box, if the number is not in the box
            if number not in box.flatten():
                # The "candidates" are the places the number could possibly go
                candidates = [
                    [1,1,1],
                    [1,1,1],
                    [1,1,1]
                ]
                # Look through each candidate with nested for loop
                for i in range(3):
                    for j in range(3):
                        # If this position is already taken up by a number
                        if box[i,j] in numbers:
                            # Eliminate the candidate
                            candidates[i][j] = 0
                        # If there's no number in that position
                        else:
                            row = (box_index//3)*3 + i 
                            column = (box_index%3)*3 + j
                            # If the number we investigating is in the row or column
                            if (number in sudoku_board[row,:]) or (number in sudoku_board[:,column]):
                                # Eliminate the candidate
                                candidates[i][j] = 0
                # Count how many possible candidates remaining
                num_candidates = np.sum(np.array(candidates).flatten())
                # If only one candidate remaining, fill it up
                if num_candidates == 1:
                    # get the index
                    i,j = np.where(np.array(candidates)==1)
                    i = int(i[0])
                    j = int(j[0])
                    candidate_row = (box_index//3)*3 + i 
                    candidate_column = (box_index%3)*3 + j
                    sudoku_board[candidate_row,candidate_column] = number 
                    print("HURRAY!")
    return sudoku_board 

In [ ]:
# Check for possibilities 
def strat2(sudoku_board_in):
    sudoku_board = sudoku_board_in.__deepcopy__(sudoku_board_in)
    return 

In [78]:
# Look at the number that shows up the most on the board
def strat1_draft(sudoku_board_in):
    sudoku_board = sudoku_board_in.__deepcopy__(sudoku_board_in)
    numbers = (1,2,3,4,5,6,7,8,9)
    highest = None
    for n in numbers:
        occurences = np.sum(sudoku_board.flatten()==n)
        if highest == None:
            highest = (n,occurences)
        elif occurences > highest[1]:
            highest = (n,occurences)
    boxes = [
        sudoku_board[0:3,0:3], # rows 0,1,2, columns 0,1,2
        sudoku_board[0:3,3:6], # rows 0,1,2, columns 3,4,5
        sudoku_board[0:3,6:9], # rows 0,1,2, columns 6,7,8
        sudoku_board[3:6,0:3], # rows 3,4,5, columns 0,1,2
        sudoku_board[3:6,3:6], # rows 3,4,5, columns 3,4,5
        sudoku_board[3:6,6:9],
        sudoku_board[6:9,0:3], # rows 6,7,8
        sudoku_board[6:9,3:6],
        sudoku_board[6:9,6:9],
    ]
    for box_index,box in enumerate(boxes):
        if highest[0] not in box.flatten():
            candidates = [
                [1,1,1],
                [1,1,1],
                [1,1,1]
            ]
            # Look through each candidate
            for i in (0,1,2):
                for j in (0,1,2):
                    # If this position is already taken up by a number
                    if box[i,j] in numbers:
                        # Eliminate the candidate
                        candidates[i][j] = 0
                    # If there's no number in that position
                    else:
                        row = (box_index//3)*3 + i 
                        column = (box_index%3)*3 + j
                        # If the number we investigating is in the row or column
                        if (highest[0] in sudoku_board[row,:]) or (highest[0] in sudoku_board[:,column]):
                            # Eliminate the candidate
                            candidates[i][j] = 0
            # Count how many possible candidates remaining
            num_candidates = np.sum(np.array(candidates).flatten())
            # If only one candidate remaining, fill it up
            if num_candidates == 1:
                # get the index
                i,j = np.where(np.array(candidates)==1)
                i = int(i[0])
                j = int(j[0])
                candidate_row = (box_index//3)*3 + i 
                candidate_column = (box_index%3)*3 + j
                sudoku_board[candidate_row,candidate_column] = highest[0]
                print("HURRAY!")
    return sudoku_board 

In [79]:
display(sudoku_0)


0 6 3 | 5 8 4 | 0 0 0 
0 2 7 | 0 0 0 | 0 8 0 
0 0 0 | 2 0 0 | 9 0 3 
---------------------
0 3 0 | 6 0 0 | 8 0 0 
0 0 0 | 8 5 9 | 0 0 0 
0 0 5 | 0 0 7 | 0 4 0 
---------------------
2 0 8 | 0 0 5 | 0 0 0 
0 4 0 | 0 0 0 | 5 3 0 
0 0 0 | 4 9 8 | 7 1 0 


In [80]:
display(strat1(strat1(sudoku_0)))

HURRAY!
HURRAY!
HURRAY!
HURRAY!
HURRAY!
HURRAY!
HURRAY!
HURRAY!
9 6 3 | 5 8 4 | 0 0 0 
0 2 7 | 9 0 0 | 0 8 0 
0 0 0 | 2 7 0 | 9 0 3 
---------------------
0 3 0 | 6 4 0 | 8 0 0 
0 0 0 | 8 5 9 | 0 0 0 
0 0 5 | 0 0 7 | 0 4 0 
---------------------
2 0 8 | 0 0 5 | 0 0 0 
0 4 0 | 0 0 0 | 5 3 8 
3 5 0 | 4 9 8 | 7 1 2 


In [67]:
np.where(np.array([[1,3],[3,3]]) == 3)

(array([0, 1, 1]), array([1, 0, 1]))

In [ ]:
i,j = np.where(np.array([[1,2],[3,4]]) == 3)
int(i[0])

1

In [11]:
arr = np.array([[1,2],[1,3]])
print(np.sum(arr.flatten()==1))

2


In [28]:
5%3

2

In [58]:
a = np.array([1,2])
b=a.__deepcopy__(a)
a[0]=5

In [59]:
a

array([5, 2])

In [60]:
b

array([1, 2])